version: '2'
services:
    librecat:
        build:
            context: .
            dockerfile: Dockerfile
        image: wordpress:4.7
        ports:
            - "80:80"
            - "443:443"
        links:
            - "mariadb:mydb"
            - "nginx:webserver"
            - "php-fpm:php"
        env_file:
            - ./conf/local.env
        depends_on:
            - nginx
            - php-fpm
        restart: always
    mariadb:
        build: mariadb
        image: mardiadb:10.1
        ports:
            - "3306:3306"
        env_file:
            - ./conf/mysql.env
        volumes:
            - "~/librecat-mysql:/var/lib/mysql"
        restart: always
    nginx:
        build: nginx
        image: nginx:1.11.6
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - ./conf/nginx.env
        volumes:
            - "~/conf/nginx.conf:/etc/nginx/nginx.conf"
        restart: always
    php-fpm:
        build: php-fpm
        image: php-fpm:7.1.0
        ports:
            - "9000:9000"
        env_file:
            - ./conf/php.env
        volumes:
            - "~/conf/php.ini:/etc/php/php.ini"
            - "~/conf/php-fpm.conf.:/etc/php/php-fpm.conf"
